#!/usr/bin/env python3
"""Regenerate constants/iucnStatus.ts and constants/avonet.ts.

Both files map IOC v15.2 common names to licensed open data, joined through the
scientific names in constants/birdLatin.ts. We ship static maps (no runtime API
calls) so the Guide tab works offline and stays commercially clean.

INPUTS (fetch these first, then pass their paths):

1. IUCN status (Wikidata P141, CC0). Wikidata's status entities no longer carry
   P528 IUCN codes, so we pull the raw status Q-id per species and map it here.
   Run at https://query.wikidata.org/ (or curl the /sparql endpoint, Accept:
   application/sparql-results+json) and save JSON:

       SELECT ?sci ?status WHERE {
         ?species wdt:P141 ?status; wdt:P171* wd:Q5113; wdt:P225 ?sci.
       }

2. AVONET (Tobias et al. 2022, Ecology Letters, CC BY 4.0):
       https://ndownloader.figshare.com/files/34480856   (AVONET ...dataset 1.xlsx)

USAGE:
   python3 scripts/build-species-data.py <wikidata.json> <avonet.xlsx>

Refresh cadence: IUCN ~once a year; AVONET is static (one published release).
"""
import sys, json, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Wikidata status entity -> IUCN code (verified 2026-06-26 by label lookup).
QCODE = {
    'Q211005': 'LC', 'Q719675': 'NT', 'Q278113': 'VU', 'Q96377276': 'EN',
    'Q219127': 'CR', 'Q237350': 'EX', 'Q239509': 'EW', 'Q3245245': 'DD',
}
# When Wikidata lists more than one assessment, keep the most-threatened.
PRIORITY = {'CR': 0, 'EN': 1, 'VU': 2, 'NT': 3, 'LC': 4, 'EW': 5, 'EX': 6, 'DD': 7}
MIG = {1: 'sedentary', 2: 'partial', 3: 'migratory'}


def load_bird_latin():
    t = open(os.path.join(ROOT, 'constants', 'birdLatin.ts')).read()
    m = re.search(r'BIRD_LATIN[^=]*=\s*(\{.*?\n\})', t, re.S)
    return eval(m.group(1))  # noqa: S307 - trusted generated source


def ioc_order():
    t = open(os.path.join(ROOT, 'constants', 'birdNames.ts')).read()
    return re.findall(r'name:\s*"((?:[^"\\]|\\.)*)"', t)


def ordered_keys(d, order):
    oset = set(order)
    return [n for n in order if n in d] + [k for k in d if k not in oset]


def build_iucn(wikidata_json, latin, order):
    raw = json.load(open(wikidata_json))
    by_sci = {}
    for r in raw['results']['bindings']:
        sci = (r.get('sci', {}).get('value', '')).strip().lower()
        q = r.get('status', {}).get('value', '').split('/')[-1]
        code = QCODE.get(q)
        if not sci or not code:
            continue
        if sci not in by_sci or PRIORITY[code] < PRIORITY[by_sci[sci]]:
            by_sci[sci] = code
    iucn = {}
    for common, lat in latin.items():
        code = by_sci.get((lat or '').strip().lower())
        if code:
            iucn[common] = code
    keys = ordered_keys(iucn, order)
    out = os.path.join(ROOT, 'constants', 'iucnStatus.ts')
    with open(out, 'w') as f:
        f.write(
            "// Generated by scripts/build-species-data.py - do not edit by hand.\n"
            "// Source: Wikidata P141 (IUCN conservation status), CC0, joined to IOC\n"
            "// v15.2 common names via constants/birdLatin.ts (scientific-name match).\n"
            "// Status itself originates with the IUCN Red List of Threatened Species.\n"
            "// Unmatched names resolve to 'NE' at runtime.\n\n"
            "import { IUCNStatusCode } from './Colors';\n\n"
            "const IUCN_STATUS: Record<string, IUCNStatusCode> = {\n")
        for n in keys:
            f.write(f"  {json.dumps(n)}: '{iucn[n]}',\n")
        f.write(
            "};\n\n"
            "// Conservation status for a species by its IOC common name. Unknown or\n"
            "// unassessed species return 'NE' (Not Evaluated).\n"
            "export function statusFor(name: string): IUCNStatusCode {\n"
            "  return IUCN_STATUS[name] ?? 'NE';\n"
            "}\n\n"
            "export default IUCN_STATUS;\n")
    print(f"wrote {out}: {len(keys)} entries")


def harvest_sheet(wb, sheet, sci_col):
    ws = wb[sheet]
    it = ws.iter_rows(values_only=True)
    hdr = list(next(it))
    idx = {h: i for i, h in enumerate(hdr)}

    def num(c):
        v = ws_row[idx[c]]
        return round(float(v), 1) if isinstance(v, (int, float)) else None

    def clean(v):
        return None if v in (None, 'NA', '', 'na') else v

    def mig(v):
        try:
            return MIG.get(int(float(v)))
        except (TypeError, ValueError):
            return None

    out = {}
    for ws_row in it:
        sci = (ws_row[idx[sci_col]] or '').strip()
        if not sci:
            continue
        out[sci.lower()] = {
            'mass': num('Mass'), 'wingChord': num('Wing.Length'),
            'habitat': clean(ws_row[idx['Habitat']]),
            'diet': clean(ws_row[idx['Trophic.Niche']]),
            'migration': mig(ws_row[idx['Migration']]),
        }
    return out


def build_avonet(xlsx, latin, order):
    import openpyxl
    wb = openpyxl.load_workbook(xlsx, read_only=True, data_only=True)
    # BirdLife primary; fill gaps from eBird then BirdTree so more IOC Latin
    # names find a match across the three taxonomies.
    av = harvest_sheet(wb, 'AVONET1_BirdLife', 'Species1')
    for sheet, col in (('AVONET2_eBird', 'Species2'), ('AVONET3_BirdTree', 'Species3')):
        for k, v in harvest_sheet(wb, sheet, col).items():
            av.setdefault(k, v)
    ioc = {}
    for common, lat in latin.items():
        rec = av.get((lat or '').strip().lower())
        if rec:
            ioc[common] = rec
    keys = ordered_keys(ioc, order)

    def fmt(v):
        if v is None:
            return 'null'
        if isinstance(v, (int, float)):
            return repr(v)
        return json.dumps(v)

    out = os.path.join(ROOT, 'constants', 'avonet.ts')
    with open(out, 'w') as f:
        f.write(
            "// Generated by scripts/build-species-data.py - do not edit by hand.\n"
            "// Source: AVONET (Tobias et al. 2022, Ecology Letters), CC BY 4.0,\n"
            "// figshare 10.6084/m9.figshare.16586228. BirdLife/eBird/BirdTree sheets\n"
            "// merged, joined to IOC v15.2 common names via constants/birdLatin.ts.\n"
            "// Attribution is mandatory (CC BY) - shown on the species Guide credit line.\n\n"
            "export type Migration = 'sedentary' | 'partial' | 'migratory';\n"
            "export interface AvonetRecord {\n"
            "  mass: number | null;       // body mass, grams\n"
            "  wingChord: number | null;  // wing length, mm\n"
            "  habitat: string | null;\n"
            "  diet: string | null;       // AVONET trophic niche\n"
            "  migration: Migration | null;\n"
            "}\n\n"
            "const AVONET: Record<string, AvonetRecord> = {\n")
        for n in keys:
            r = ioc[n]
            f.write(
                f"  {json.dumps(n)}: {{ mass: {fmt(r['mass'])}, wingChord: {fmt(r['wingChord'])}, "
                f"habitat: {fmt(r['habitat'])}, diet: {fmt(r['diet'])}, migration: {fmt(r['migration'])} }},\n")
        f.write(
            "};\n\n"
            "// AVONET morphology + ecology for a species by its IOC common name.\n"
            "// Returns null when the species isn't in AVONET (drives the '-' UI state).\n"
            "export function avonetFor(name: string): AvonetRecord | null {\n"
            "  return AVONET[name] ?? null;\n"
            "}\n\n"
            "export default AVONET;\n")
    print(f"wrote {out}: {len(keys)} entries")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    latin = load_bird_latin()
    order = ioc_order()
    build_iucn(sys.argv[1], latin, order)
    build_avonet(sys.argv[2], latin, order)


if __name__ == '__main__':
    main()
